server:
  port: 8260

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO

spring:
  data:
    mongodb:
      host: localhost
      database: humpback_dev
      port: 27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://[keycloak_host]/auth/realms/humpback_dev
          jwk-set-uri: http://[keycloak_host]/auth/realms/humpback_dev/protocol/openid-connect/certs


storage:
  minio:
    endpoint: http://localhost:9000
    accesskey: minio
    secretkey: miniostorage
    buckets:
      image: humpback-image